name: Deploy to servers

on:
  push:
    branches:
      - main

env:
  DEPLOY_HOST1: example.com
  DEPLOY_HOST2: another-example.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the application
      run: |
        # commands to build the application

    - name: Deploy to first server
      env:
        DEPLOY_HOST: ${{ env.DEPLOY_HOST1 }}
      run: |
        # commands to deploy the build to the first server

    - name: Deploy to second server
      env:
        DEPLOY_HOST: ${{ env.DEPLOY_HOST2 }}
      run: |
        # commands to deploy the build to the second server
