name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest

    steps:
    - name: Greet Contributor
      if: github.event_name == 'pull_request'
      run: echo "Thank you for your pull request!"
      
    - name: Greet Issue Opener
      if: github.event_name == 'issues'
      run: echo "Thank you for opening an issue!"
